### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR

### ISSUE THREAD

**Issue by ryosukenakagiri** [imdadahad/automate-spotify-python#1]
I got below error. Please help.

youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

**Comment by imdadahad** [comment]
Closing issue as owner described resolution:

```
I tried below command which mentioned in https://github.com/ytdl-org/youtube-dl/issues/4816:


pip3 install certifi
AND
/Applications/Python\ 3.8/Install\ Certificates.command
```
