### ISSUE TITLE
List of songs added to Spotify playlist

### ISSUE THREAD

**Issue by adrianghub** [imdadahad/automate-spotify-python#6]
Hi @imdadahad 

Recently I've come up with the issue that whenever I try to fetch songs from a selected playlist there is a response with attempting to add 0 songs ( as if there are no songs in the chosen playlist ). ` print(songs)` returns an empty list. I've tried the same cloning this project and end up with the same response. Other playlists are acting equally.
Attached there is a snapshot showing the mentioned response.
Appreciate your support in advance!

![image](https://user-images.githubusercontent.com/44274979/96417298-65f0c300-11f1-11eb-8831-7b3974f99aae.png)

**Comment by adrianghub** [comment]
I've managed to update the songs list but then another error appeared. ( the same on this cloned repo )

```
0: QuarantineMix
Enter your choice: 0
You selected: QuarantineMix
Attempting to add 1
Traceback (most recent call last):
  File "run.py", line 30, in <module>
    run()
  File "run.py", line 22, in run
    spotify_song_id = spotify_client.search_song(song.artist, 
song.track)
  File "C:\Users\adria\Desktop\automate-spotify-python\spotify_client.py", line 21, in search_song
    results = response_json['tracks']['items']
KeyError: 'tracks'
```

**Comment by adrianghub** [comment]
```
0: QuarantineMix
Enter desired playlist number: 0
Selected playlist name: QuarantineMix
Attempting to add 1
{'error': {'status': 401, 'message': 'The access token expired'}}
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    run()
  File "main.py", line 29, in run
    spotify_song_id = spotify.search_song(song.artist, song.track)
  File "C:\Users\adria\Desktop\Main\DIARY-JOUR\python-programming-studio\hacktoberfest2020\yttospotify-playlist-uploader\spotify.py", line 21, in search_song 
    results = response_json['tracks']['items']
KeyError: 'tracks'
```

**Apparently, there was a problem with an expired auth token.**


Now I have this response.  `print(song)` returns <mark>`song.Song object at 0x04186040`</mark> and after all `song.artist` as `None` is added to Spotify liked songs.


```
0: QuarantineMix
Enter desired playlist number: 0
Selected playlist name: QuarantineMix
Attempting to add 1
<song.Song object at 0x04186040>
Successfully added None to Spotify liked songs
```

**Comment by adrianghub** [comment]
![image](https://user-images.githubusercontent.com/44274979/96421885-a05d5e80-11f7-11eb-8b0e-18ad407e872f.png)

**Comment by imdadahad** [comment]
@adrianghub are you still facing this issue?

**Comment by imdadahad** [comment]
Feel free to reopen if you're having issues.
